development:
  adapter: mysql2
  host: ubuntu
  encoding: utf8
  collation: utf8_bin
  reconnect: false
  database: corpora_development
  pool: 2
  username: root
  password:

production:
  adapter: mysql2
  reconnect: true
  database: corpora
  username: root
  password: 
  host: localhost
  encoding: utf8
  collation: utf8_bin
